@echo off
echo Starting PostgreSQL Database...
pg_ctl start -D "G:\Program Files\PostgreSQL\17\data"
echo Starting SimpleATS Backend...
start cmd /k "cd backend && python server.py"
echo Starting SimpleATS Frontend...
cd frontend && npm start
